[board]
type = 'charuco'
squares_x = 7
squares_y = 5
square_length = 0.0295
marker_length = 0.0206

[detection]
#Dictionary options:
#DICT_4X4_50=0, DICT_4X4_100=1, DICT_4X4_250=2, DICT_4X4_1000=3,
#DICT_5X5_50=4, DICT_5X5_100=5, DICT_5X5_250=6, DICT_5X5_1000=7,
#DICT_6X6_50=8, DICT_6X6_100=9, DICT_6X6_250=10, DICT_6X6_1000=11,
#DICT_7X7_50=12, DICT_7X7_100=13, DICT_7X7_250=14, DICT_7X7_1000=15,
#DICT_ARUCO_ORIGINAL = 16
charuco_dictionary = 8

[recording]
master_worker = 1

# Possible workers are: prophesee, basler
[[recording.workers]]
type = "basler"
placement = 1
cam_uuid = "\\\\?\\usb#vid_2676&pid_ba05&mi_00#7&2d68863b&1&0000#{79bfeeca-947f-11e1-bc58-001b2163ef96}"

[[recording.workers]]
type = "prophesee"
accumulation_time = 33333
placement = 0
save_event_file = true
falling_edge_polarity = 1
cam_uuid = "Prophesee:hal_plugin_prophesee:00051770"