## This is an example config file.
# Required variables are shown as uncommented without any value behind it
# Optional variables are commented with its default value.

# –––––––-–––––––––---------------------------------- [oard] CONFIG ----------------------------------–––––––––––––––– #
# Here the details about the board can be described
[board]
# The board type at the moment this can only be "charuco"
type =

# The amount of squares in the x and y direction defaults are
#squares_x = 7
#squares_y = 5

# These variables are needed for creating a board and are defined in pixel values
#square_pixel_length = 100
#marker_pixel_length = 70

# Margins are the space between the edge of the image and the board itself, default value is
# the square_pixel_length - marker_pixel_length
#margin_size = 30

# Defines how many bits/pixels wide the border will be of the charuco markers
#border_bits = 1

# These values are important from recording and onward, they need to be physically measured on the screen you will be
# showing your board on
square_length =
marker_length =

[detection]
#Dictionary options:
#DICT_4X4_50=0, DICT_4X4_100=1, DICT_4X4_250=2, DICT_4X4_1000=3,
#DICT_5X5_50=4, DICT_5X5_100=5, DICT_5X5_250=6, DICT_5X5_1000=7,
#DICT_6X6_50=8, DICT_6X6_100=9, DICT_6X6_250=10, DICT_6X6_1000=11,
#DICT_7X7_50=12, DICT_7X7_100=13, DICT_7X7_250=14, DICT_7X7_1000=15,
#DICT_ARUCO_ORIGINAL = 16
#opencv_aruco_dictionary = 8
#detection_interval = 2
#minimum_corner_fraction = 0.125

# Here you can customise the ChArUco detection parameters, an explanation on what each value does is described by OpenCv:
# https://docs.opencv.org/4.13.0/df/d01/structcv_1_1aruco_1_1CharucoParameters.html
[detection.charuco_parameters]
#refine = false
#min_markers = 2

# Here you can customise the aruco detection parameters, an explanation on what each value does is described by OpenCv:
# https://docs.opencv.org/4.13.0/d1/dcd/structcv_1_1aruco_1_1DetectorParameters.html
[detection.detector_parameters]
#adaptiveThreshWinSizeMin = 3
#adaptiveThreshWinSizeMax = 23
#adaptiveThreshWinSizeStep = 10
#adaptiveThreshConstant = 7
#minMarkerPerimeterRate = 0.03
#maxMarkerPerimeterRate = 4.
#polygonalApproxAccuracyRate = 0.03
#minCornerDistanceRate = 0.05
#minDistanceToBorder = 3
#minMarkerDistanceRate = 0.05
#cornerRefinementMethod = 0
#cornerRefinementWinSize = 5
#cornerRefinementMaxIterations = 30
#cornerRefinementMinAccuracy = 0.1
#markerBorderBits = 1
#perspectiveRemovePixelPerCell = 4
#perspectiveRemoveIgnoredMarginPerCell = 0.13
#maxErroneousBitsInBorderRate = 0.35
#minOtsuStdDev = 5.0
#errorCorrectionRate = 0.6
#aprilTagQuadDecimate = 0.0
#aprilTagQuadSigma = 0.0
#aprilTagMinClusterPixels = 5
#aprilTagMaxNmaxima = 10
#aprilTagCriticalRad = 0.174533
#aprilTagMaxLineFitMse = 10.0
#aprilTagMinWhiteBlackDiff = 5
#aprilTagDeglitch = 0
#detectInvertedMarker = false
#useAruco3Detection = false
#minSideLengthCanonicalImg = 32
#minMarkerLengthRatioOriginalImg = 0.0

[recording]
master_worker =
#fps = 30
#detection_interval = 2

# Possible workers are: prophesee, basler
[[recording.workers]]
type = "basler"
placement =
#cam_uuid =

[[recording.workers]]
type = "prophesee"
placement =
#cam_uuid =
#accumulation_time = 33333
#save_event_file = true
falling_edge_polarity =
#bias_diff =
#bias_diff_on =
#bias_diff_off =
#bias_fo =
#bias_hpf =
#bias_refr =

#enable_erc =
#erc_rate =

#enable_etf =
#etf_mode =
#etf_threshold =

[viewing]
#views_horizontal = 3

